version: '3'

services:
  postgres:
    image: postgres:14
    container_name: RensReminder-postgres
    env_file:
      - .env
    volumes:
      - renstask-postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  renstask-postgres-data: